### ISSUE TITLE
Destroy method

### ISSUE THREAD

**Issue by mrkenng** [Arttse/jquery.auto-text-rotating#6]
I've been using your script for a while and really liked it. Was wondering if there's any destroy method? Or stop does the job in this case? The reason because I'm using it with react and wanted to destroy on unmount.

**Comment by Arttse** [comment]
Hi @mrkenng! Thanks for using this script. For destroy you can use `stop` method, in React.js like that:
```js
componentWillUnmount() {
  $('.element').atrotating('stop');
}
```
Also you can try with [settings](https://github.com/Arttse/jquery.auto-text-rotating#settings-stop-method)

**Comment by mrkenng** [comment]
Thank you @Arttse ! Just making sure :) Great work by the way!
